spring:
  application:
    name: Demo
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          jsonplaceholder:
            url: https://jsonplaceholder.typicode.com/

#logging:
#  level:
#    com.example.demo: debug
